name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches-ignore:
      - releases

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: corepack enable && corepack enable npm
      - run: npm ci
      - run: npm run all
      - uses: actions/upload-artifact@v4
        with: 
          name: built
          if-no-files-found: error
          path: |
            dist
            action.yml
            helloworld/main.exe

  test: # make sure the action works on a clean machine without building
    needs: [build]
    strategy:
      matrix: 
        on:
          - windows-latest
    runs-on: ${{ matrix.on }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: built

      # using demo account
      # https://www.ssl.com/guide/esigner-demo-credentials-and-certificates/
      - uses: ./
        with:
          mode: sandbox
          username: esigner_demo
          password: esignerDemo#1
          totp-secret: RDXYgV9qju+6/7GnMf1vCbKexXVJmUVr+86Wq/8aIGg=


      - name: Select Certificate From Windows Store
        shell: powershell
        run: |
          $CodeSigningCert = Get-ChildItem Cert:\CurrentUser\My -CodeSigningCert | Select-Object -First 1
          echo "THUMBPRINT: $($CodeSigningCert.Thumbprint)"
          echo "THUMBPRINT=$($CodeSigningCert.Thumbprint)" >> $env:GITHUB_ENV

      - name: Sign helloworld.exe
        shell: powershell
        run: |
          $THUMBPRINT = $env:THUMBPRINT
          & 'C:/Program Files (x86)/Windows Kits/10/bin/10.0.22621.0/x86/signtool.exe' `
            sign /fd SHA256 /sha1 "$THUMBPRINT" /d "HelloWorld.exe" /tr "http://ts.ssl.com" /td sha256 "helloworld/main.exe"

  conclude:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs:
      - build
      - test
    steps:
      - name: Conclude Tests
        env: { NEEDS: "${{ toJSON(needs) }}" }
        run: |
          echo "$NEEDS" | jq -c '. | to_entries[] | [.key, .value.result]'
          echo "$NEEDS" | jq -e '. | all(.result == "success")' > /dev/null
